### ISSUE TITLE
优化Governance的登陆态有效期

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#102]
**Describe the bug**
governance的登陆态时间设置太短，不符日常合办公习惯。

**To Reproduce**
1. 登陆governance
2. 过一段时间不操作
3. 登陆态自动失效

**Expected behavior**
登陆态的失效时间可以配置，默认一天/24小时后失效。

**Comment by puremilkfan** [comment]
solution
在application.properties里面设置登陆态的失效时间为24小时
