### ISSUE TITLE
自动生成在线文档

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#110]
**Is your feature request related to a problem? Please describe.**
现在需要手动执行程序，将https://github.com/WeBankFinTech/WeEvent-docs 项目里的内容生成在线文档https://weeventdoc.readthedocs.io/zh_CN/latest/。

**Describe the solution you'd like**
当文档项目WeEvent-docs有PR合入时，自动生成在线文档到
https://weeventdoc.readthedocs.io/zh_CN/latest/

**Comment by cristicmf** [comment]
add the url to the webhooks config
