### ISSUE TITLE
当用户没有安装WeBase的时候，优化Governance页面的提醒

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#134]
**Is your feature request related to a problem? Please describe.**
当用户没有安装WeBase的时候，区块链节点相关的页面都无法正常使用。

**Describe the solution you'd like**
尽量通过Broker访问区块链。
当用户没有安装WeBase时，区块链节点相关的页面需要更加友好的提示。
区块链节点相关的信息：
1、当前节点、pbftview及版本信息
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getnodeidlist
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getclientversion
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getpbftview
2、当前交易数量和块高、待打包的交易数量
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#gettotaltransactioncount
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getpendingtxsize
3、遍历区块和交易
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getblockbynumber
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#gettransactionreceipt
注意这里要特别关注logs字段。可能的话，解析出来。

**Comment by saintping** [comment]
包括用户配置了WeBase的URL，但是访问异常。也需要更加友好的提示。

**Comment by puremilkfan** [comment]
the problem
1-当用户没有安装WeBase的时候，区块链节点相关的页面都无法正常使用。

the solution 
1-WeBase是通过访问fisco取得数据然后返回给governance使用，在2.0版本 可以通过broker直接访问·fisco取到节点的数据返回给governance使用，而不必一定要配置WeBase
