### ISSUE TITLE
优化IWeEventClient的接口重载

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#136]
**Is your feature request related to a problem? Please describe.**
Java SDK的IWeEventClient接口，对于需不需要groupid，有两大类相似的接口。API定义有一点繁琐。

**Describe the solution you'd like**
实现上在build方法创建对象时输入可选参数groupid，将IWeEventClient对象和groupid绑定。
减少一半的api接口，使用户接口更清晰。

**Comment by saintping** [comment]
java sdk的样例有点复杂，可以更简单一点。
https://github.com/WeBankFinTech/WeEvent/blob/master/weevent-broker/src/test/java/com/webank/weevent/sample/JavaSDK.java

**Comment by anyspa** [comment]
1、通过构建IWeEvent实例时，传入groupId，减少一半的接口重载
