### ISSUE TITLE
优化spring boot服务的bash启动脚本

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#144]
**Is your feature request related to a problem? Please describe.**
1、Java虚拟机的目录选择不是很友好。需要用户设置一些系统变量，不同的发行版差异很大。
2、Java虚拟机的启动参数，现在是最小内存512M。这个限制太强了，也没有必要。
JAVA_OPTS="-Xverify:none -XX:TieredStopAtLevel=1 -Xms512m -Xmx2048m -XX:NewSize=256m -XX:MaxNewSize=1024m -XX:PermSize=128m -XX:+DisableExplicitGC"
进程的最小内存需要512M，在配置比较低的机器或者虚拟机里，会启动失败。

**Describe the solution you'd like**
1、关于虚拟机目录，只依赖JAVA_HOME变量。
在启动bash脚本里设置。
JAVA_HOME=
CLASSPATH=.:${JAVA_HOME}\lib;${JAVA_HOME}\lib\tools.jar
Java程序启动方式如：${JAVA_HOME}/bin/java ***

2、Broker和Governance模块默认的启动参数如下
需要在启动脚本里做一个判断，在配置比较低的机器上，比如内存小于1G。不加内存相关参数启动JAVA_OPTS="-Xverify:none -XX:+DisableExplicitGC"。确保程序在虚拟机或者树莓派等低端机器上也能够运行。

3、所有spring boot服务遵循同样的启动规范，启动脚本应该是同一份。例如broker服务的启动broker.sh和governance的启动脚本governance.sh，除了名字不同，里面的bash内容应该完全一致。

**Comment by anyspa** [comment]
1、执行一键安装脚本前，config.properties 需要多配置一个JAVA_HOME的参数，
2、如果是单独调用启停脚本时，先检查脚本是否已经配置了JAVA_HOME，如果没有则必须手动配置
3、支持在小于1G的服务器上运行
4、实现启动脚本共用
PR #144
