### ISSUE TITLE
将SQL语句从Java代码中抽取到独立的sql文件

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#150]
**Is your feature request related to a problem? Please describe.**
SQL不应该直接写在Java代码里
https://github.com/WeBankFinTech/WeEvent/blob/master/weevent-governance/src/main/java/com/webank/weevent/governance/initial/InitialDb.java

**Describe the solution you'd like**
将SQL放到独立的.sql文件中，Java读取文件来执行。

**Comment by puremilkfan** [comment]
Describe the solution you'd like
1.SQL文件放在Java代码中不便于维护，将其中的创建库表格语句独立出来
2.每次创建数据库表之前判断库是否存在，如果存在则抛出异常，并提示表格已经存在。
3.测试修改之后sql语句的正确性，确保数据库表在项目初始化时可以正常创建
