### ISSUE TITLE
主动探测区块链节点版本

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#155]
**Is your feature request related to a problem? Please describe.**
WeEvent部署的时候，需要用户填区块链版本。fisco.properties#version和config.properties#fisco-bcos.version。服务初始化的时候，并没有判断节点的版本是否一致。

**Describe the solution you'd like**
WeEvent服务初始化的时候，通过web3sdk的接口获取节点后台版本号。和用户配置的做一个比对。
如果发现异常，服务应该给出友好的提示，然后退出。
WeEvent初始化时，通过接口https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getclientversion

**Comment by saintping** [comment]
2.0的版本获取版本号的接口为web3j.getNodeVersion()。
1.3的版本获取版本号的接口为web3j.web3ClientVersion()。这个接口的返回是
“eth/v1.3.7/Linux/g++/Interpreter/RelWithDebInfo/dedd8553/”

**Comment by anyspa** [comment]
#155
1、服务初始化的时候，判断用户配置的区块链节点版本号与从区块链节点获取的版本号是否一致
2、FiscoConfig中添加orgId和account默认初始化值
