### ISSUE TITLE
检查用户输入的群组ID

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#156]
**Is your feature request related to a problem? Please describe.**
1.0.0版本是通过配置来检查群组ID，这个配置已经被issues#163优化掉。

**Describe the solution you'd like**
通过接口检查群组ID的合法性。避免不必要的配置隐患。
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getgrouplist
同时在内存里缓存一份列表，避免频繁调用。

**Comment by anyspa** [comment]
#156
1、在服务初始化时，查询节点得到群组Id，并缓存到内存中，所有查询、检查groupId都从缓存中获取
