### ISSUE TITLE
Governance页面支持群组

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#157]
**Is your feature request related to a problem? Please describe.**
Governance管理还没有群组，默认展示的是群组1的数据。

**Describe the solution you'd like**
当用户选择了某个WeEvent视图后，如果是FISCO 2.0版本应该动态拉取群组列表。
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/api.html#getgrouplist
让用户选择群组ID，后续的其他接口都需要群组ID的参数。不再使用默认的群组ID=1。
![image](https://user-images.githubusercontent.com/4252571/62126533-77a32d80-b302-11e9-8a66-cb2e3ed65a47.png)

**Comment by anyspa** [comment]
#157
Governance页面新增群组列表，可以随意切换到其他群组，显示改群组的订阅列表信息等
