### ISSUE TITLE
增加获取WeEvent版本的接口

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#159]
**Is your feature request related to a problem? Please describe.**
WeEvent服务里现在没有带编译和版本信息。为了更好的版本管理，需要增加一个在运行期获取版本的接口。

**Describe the solution you'd like**
1、WeEvent提供版本CGI接口
WeEvent版本号维护在build.gradle文件里allprojects.version
Broker编译的时候，将这个版本信息带到jar包里，还包括如下信息。
"Build Time": "20190106 20:49:10",
"Git Branch": "master",
"Git Commit Hash": "693a709ddab39965d9c39da0104836cfb4a72054"

2、在Governance的编辑服务页面上，通过这个接口判断WeEvent的URL是否正确。
并且将这些信息在页面上显示给用户看。
![image](https://user-images.githubusercontent.com/4252571/62282670-857fbc80-b482-11e9-8892-0ae1f5022f90.png)

**Comment by anyspa** [comment]
#159
1、新增获取WeEvent版本信息接口
2、优化新增/修改Governance服务时，检验填写的broker、webase服务是否正常
