### ISSUE TITLE
优化Governance的订阅列表页面

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#176]
**Is your feature request related to a problem? Please describe.**
1、Governance的订阅列表中，没有关于订阅来源的信息，比如订阅时间、订阅来源IP。不容易看出问题。
![image](https://user-images.githubusercontent.com/4252571/62990182-97e3f800-be7d-11e9-8e5c-fa6909ee8238.png)
2、同时主题字段的值都统一附加了[]，这个很容易引起歧义，去掉这个内容。
3、如果主题比较多，无法很快确定主题是否存在。

**Describe the solution you'd like**
1、订阅列表中加上订阅时间和来源IP。
2、同时给主题列的值上加一个快捷按钮，效果等于跳转到主题管理页上搜索这个主题。

**Comment by saintping** [comment]
issue #187已经去掉了主题上的[]。同时，只要订阅的时候加了是否存在的判断，也就是订阅成功的主题肯定是存在的。

**Comment by anyspa** [comment]
#176

**Comment by anyspa** [comment]
#176
1、订阅列表中加上订阅时间和来源IP
2、增加从订阅列表点击topic直接跳转到topic详情界面
