### ISSUE TITLE
将区块链插件配置成bean

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#231]
**Is your feature request related to a problem? Please describe.**
区块链插件的实现比如FiscoBcosDelegate，是bean比如IProducer和IConsumer的static成员。
这样会有一个问题，Spring重新装载IProducer和IConsumer时并不会重新初始化FiscoBcosDelegate。
自动化测试用例测试不同的区块链时，需要用到@DirtyContext来重新重新装载上下文。

**Describe the solution you'd like**
将区块链插件配置成bean，支持重新装载。

**Comment by anyspa** [comment]
PR #406
