### ISSUE TITLE
代码中不一致的null检查

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [WeBankFinTech/WeEvent#240]
**Describe the bug**
上下文中不一致的null检查:
https://github.com/WeBankFinTech/WeEvent/blob/e1a02835907703e8b5ac0e856ac49e4d8a08659c/weevent-broker/src/main/java/com/webank/weevent/protocol/rest/AdminRest.java#L145-L146
在145行处使用 tbTransHashes没有做null检查,
在146行处使用 tbTransHashes又做了null检查,
同时145行和146行之间的代码没有对tbTransHashes进行赋值,
这样导致逻辑冲突，漏掉或者多余一处null检查,
同样的问题存在于此文件的174行和200行处。

**Comment by saintping** [comment]
totalCount字段已经删除
