### ISSUE TITLE
String类型又调用了toString()方法

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [WeBankFinTech/WeEvent#241]
**Describe the bug**
https://github.com/WeBankFinTech/WeEvent/blob/03b74353adaa47c0baf08676d5684e300cb0ec7d/weevent-client/src/main/java/com/webank/weevent/sdk/jms/WeEventStompCommand.java#L144
文件144行get(0)返回类型是String,重复调用了toString()方法。

**Comment by saintping** [comment]
已经修复。
