### ISSUE TITLE
Governance管理端Review建议

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#286]
**Describe the bug**
问题模块 | 问题描述 | 分类
-- | -- | --
用户注册 | 用户邮箱配置为可选,   如无则无法进行密码重置 | 优化
数据概览 | 数据概览部分第一次进入时没有数据 | bug
数据概览 | 数据概览页面的图表改成默认展示最近一周的事件数并支持时间选择 | 优化
交易详情 | 后台对于交易页面显示的内容根据前端传入参数进行筛选 | bug
交易详情 | 交易列表点击查看详情 没有数据显示 | bug
节点列表 | 节点列表调整节点名称显示的长度 | 优化
订阅列表 | 订阅列表放置到主题列表和事件统计中间 | 优化
订阅列表 | 订阅列表拆分成两个部分（机器列表下拉 ,   显示对应的节点列表） | 优化
规则管理 | 移除‘ “”使用文档”   “"验证规则" "规则语法说明" 这几个页面文字描述 | 优化
规则管理 | ”数据流转" 改成 数据来源并改为下拉选项 并支持翻页 | 优化
规则管理 | 编辑规则的流程修改   （1.选择数据来源  2.选择字段 3.设置条件 4,流转操作） | 优化
规则管理 | Processor提供规则条件是否正确的接口 | 优化

**Comment by anyspa** [comment]
PR #307
