### ISSUE TITLE
统一Java服务依赖jar包的版本

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#324]
**Is your feature request related to a problem? Please describe.**
WeEvent工程采用Gradle子模块的方式组织。各子模块引入Jar包的时候各自控制版本。
会造成生成的服务里有不同的版本的Jar包，带来隐患。

**Describe the solution you'd like**
所有的依赖Jar包，统一定义在父模块的Gradle的属性里。其他子模块继承使用。
如
属性定义
ext {
        jackson2Version = "2.9.7"
}

使用方
dependencies {
        implementation("com.fasterxml.jackson.core:jackson-databind:${jackson2Version}")
}

**Comment by dupond500** [comment]
Nice

**Comment by dupond500** [comment]
Nice

**Comment by khizar123137** [comment]
hello cocos website my withdraw is pending why is 4 days?

**Comment by anyspa** [comment]
PR #395
