### ISSUE TITLE
一键安装时的用户权限问题

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#357]
**Describe the bug**
一键安装脚本install-all.sh，nginx默认是使用nobody运行。
当用户在root用户下执行install-all.sh，将服务安装到root用户下，会引起Governance访问失败。

**To Reproduce**
1. 修改默认配置，选择安装Governance和Processor模块
2. 在root根目录下执行install-all.sh -p /root/weevent
3. /root/weevent/start-all.sh启动服务
4. 通过浏览器访问Governance
http://localhost:8080/weevent-governance

nginx日志
2019/11/14 19:52:23 [crit] 20592#0: *20 open() "/root/WeEvent-1.1.0/nginx/./nginx_temp/proxy/0000000006" failed (13: Permission denied) while reading
 upstream, client: x.x.x.x, server: , request: "GET /weevent-governance/static/css/app.1dcfc48c42732d52685c4e69cf6a01d1.css.map HTTP/1.1", ups
tream: "http://127.0.0.1:7009/weevent-governance/static/css/app.1dcfc48c42732d52685c4e69cf6a01d1.css.map", host: "x.x.x.x:8080"

**Expected behavior**
用户使用某个账号一键安装install-all.sh，需要把nginx的运行账号也改成这个账号。

**Comment by anyspa** [comment]
PR #368
