### ISSUE TITLE
编辑Broker服务的操作优化

### ISSUE THREAD

**Issue by puremilkfan** [WeBankFinTech/WeEvent#385]
**Is your feature request related to a problem? Please describe.**
broker操作，有2个需要优化的地方

**Describe the solution you'd like**
1.目前删除broker时，和broker相关连的其他表数据没有同步删除，成为了垃圾数据,需要同步删除。

2.修改broker的时候，如果变更了broker url,没有同步删除规则引擎里面对应的规则，这会造成有多余的订阅。需要同步删除规则引擎里面对应的规则，并且新增和新的broker服务对应的内置规则引擎。

**Comment by saintping** [comment]
Broker关联的规则状态在Governance上没有任何提现。
这个需要加强，可以在编辑服务显示关联的内置规则ID及当前其运行状态。
