### ISSUE TITLE
使用spring-boot-starter-data-redis代替jedis

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#387]
**Is your feature request related to a problem? Please describe.**
Broker支持将事件缓存在redis里以提高事件通知的性能，使用的是jedis客户端。
spring有内置的redis集成方案spring-boot-starter-data-redis。在连接池的处理以及集成上都更加简单。

**Describe the solution you'd like**
使用spring-boot-starter-data-redis方案替换当前的jedis方案。

**Comment by saintping** [comment]
使用函数缓存

**Comment by anyspa** [comment]
PR #402
