### ISSUE TITLE
fastJson 换成 jackson

### ISSUE THREAD

**Issue by puremilkfan** [WeBankFinTech/WeEvent#388]
**Is your feature request related to a problem? Please describe.**
目前 governance、robust、processor使用fastJson序列化/反序列化，实际使用过程中，fastjson的高级特性支持不完善、存在bug、得不到英文社区的支持，导致开发人员在业务实际应用时反而需要较多的时间去调试定位类库本身的问题。

**Describe the solution you'd like**
使用jackson代替fastjosn,它有更完善的扩展机制,更加遵循java标准。

**Comment by saintping** [comment]
直接依赖替换为jackson
间接依赖强制版本1.2.60
