### ISSUE TITLE
MQTT协议支持订阅持久化

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#447]
**Is your feature request related to a problem? Please describe.**
直到v1.2.0版本，MQTT协议只支持Qos=0和1，没有支持Qos=2。Qos=1的情况下，当订阅者离线，上线后再重新订阅时，离线阶段的消息是收不到的。
在STOMP协议中，WeEvent是通过让订阅方自己记录偏移来实现这种离线消息接收的。通过扩展STOMP标准协议，加入了自定义头offset，重新订阅时由客户端可以传入之前的offset，后台会从offset的位置开始推送通知消息。
MQTT消息不支持这种字段扩展，MQTT处理离线消息的方案是clean session标志位=0，以及通过唯一的clientid来持久化订阅。不管订阅者是否在线，订阅是持久化在Broker后端的。订阅者连接上线后，后端知道从哪个偏移位置开始推送通知消息。

**Describe the solution you'd like**
WeEvent支持MQTT协议的clean session flag=0和clientid的持久化。
clientid->subscriptionid->offset的对应关系可以持久化在服务后台（或者zookeeper里，如果有的话）。
订阅者上线后，无论订阅连接被路由到哪个服务进程，都有能力从offset位置开始推送消息。

**Comment by Owenli614625** [comment]
需求就是在客户订阅了某个主题后，保证订阅方能收到自订阅时间点以后的所有消息事件，如果订阅方离线，就要有记录，那些消息没有送达订阅方，当订阅方上线时，能及时送达。（MQTT协议 ）

**Comment by saintping** [comment]
已经合入PR #564。
使用相同的client id连接，并且clean session flag设置为0。订阅就可以收到离线消息。
如果服务有配置zookeeper，则持久化信息保存在zookeeper里。
如果服务没有配置zookeeper，则持久化信息保存在broker的内存里，broker服务重启会丢失。
