### ISSUE TITLE
weevent-broker的Restful CGI返回结构统一加上错误头

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#466]
**Is your feature request related to a problem? Please describe.**
WeEvent1.2.0之前的代码，Broker里的Restful CGI的返回格式。返回包和异常是平级的。比如这个
"http://localhost:8080/weevent-broker/rest/publish?topic=com.weevent.test&groupId=1&content=123456&weevent-format=json"
正常返回是
```
{
    "topic": "com.weevent.test",
    "eventId": "2cf24dba-59-1124",
    "status": "SUCCESS"
}
```
异常返回是
```
{
    "code": "xxxxxx",
    "message": "xxxxxxx",
}
```
这给使用方解析json时带来困扰。需要统一加一下错误码头，使客户端容易解析。

**Describe the solution you'd like**
返回的结构信息统一加上
```
{
    "code": "0",
    "message": "success",
    "data" : {}
}
```
上面那个CGI正常返回为
```
{
    "code": "0",
    "message": "success",
    "data" : {
        "topic": "com.weevent.test",
        "eventId": "2cf24dba-59-1124",
        "status": "SUCCESS"
    }
}
```
异常返回为
```
{
    "code": "xxx",
    "message": "xxx"
}
```
这样使客户端用一个模板类统一处理成为可能。
```
public class BaseResponse<T> {
    int code;
    String message;
    T data;
}
```

**Comment by anyspa** [comment]
PR #559
