### ISSUE TITLE
Linux上一键安装后gateway的配置文件是DOS格式

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#482]
**Describe the bug**
一键安装脚本安装后，gateway的配置文件是DOS格式。
需要和其他文件一致，改为Unix格式。
![image](https://user-images.githubusercontent.com/4252571/75409189-f6bd1a80-5952-11ea-9b75-29fa3bc4db44.png)

**To Reproduce**
1. 通过一键安装脚本install-all.sh安装1.2.0版本。

**Comment by anyspa** [comment]
PR #482
