### ISSUE TITLE
移除weevent-client.jar里的json rpc依赖

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#505]
**Is your feature request related to a problem? Please describe.**
weevent-client.jar访问后台，包括了三种方式：一种是STOMP，一个种是Restful，一种是JsonRPC。
Restful和JsonRPC有重复。基于简化客户端依赖，方便协议升级的考虑。
这里考虑将JsonRPC实现的几个功能，改为使用Restful实现。

**Describe the solution you'd like**
将现有weevent-client.jar里调用JsonRPC的open/close/exist/getEvent的方法，改为调用Restful调用。

**Comment by anyspa** [comment]
PR #561
