### ISSUE TITLE
WeEvent版本依赖关系

### ISSUE THREAD

**Issue by leiletea** [WeBankFinTech/WeEvent#533]
WebEvent broker执行deploy-topic-control.sh

出现如下异常：
2020-03-19 11:32:17.655 ERROR [15251-1 main] [Service.java:349 run] system error 
java.lang.Exception: Can not connect to nodes success, please checkout the node status and the sdk config!

版本信息：
broker 1.1.0    
fisco-bcos 2.2.0

经过排查，发现需要升级web3sdk的包   由2.1.1 升级为2.2.2

安装文档中并未指出需要升级web3sdk包的情况，希望能在文档中说明此类情况.

**Comment by saintping** [comment]
因为Web3SDK和FISCO-BCOS现在有比较强的依赖关系。
确实是有FISCO-BCOS 2.2需要Web3SDK 2.2的情况。跟着而来的是WeEvent也有这种版本依赖关系。
比如
WeEvent 1.1 -> Web3SDK 2.1 -> FISCO-BCOS 2.1
WeEvent 1.2 -> Web3SDK 2.2 -> FISCO-BCOS 2.2
不建议绕过WeEvent，通过直接替换Web3SDK版本版本的方式去解决类似的问题。
因为WeEvent使用哪个版本的Web3SDK是有各种考虑的，而且经过充分验证。
随意的替换版本可能会带来隐藏问题。

我们在每个版本的WeEvent文档里，都会详细写上这个版本对应的Web3SDK和FISCO-BCOS版本是什么。
