### ISSUE TITLE
将weevent-file大文件传输功能集成进Governance

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#563]
**Is your feature request related to a problem? Please describe.**
WeEvent支持大文件传输功能。因为涉及到传输通道的配置以及权限证书的管理。这个流程是比较复杂的。需要提供一种用户简单的管理页面来操作。

**Describe the solution you'd like**
为用户提供两种接入方式：
1、一种是直接通过weevent-file.jar传输文件。这种不需要依赖代理服务，但是主题、通道、证书、临时文件的存储等由使用方管理。这个参见issue #548。
2、一种是直接在governance页面上提供文件上传和下载功能。提供的能力有：
- 传输通道的编辑，包括新增，查询，修改，删除。以主题为中心以及对应证书的公私钥。
- 文件上传，包括从本地文件系统选择文件，选择通道等。
- 文件下载，包括拉取历史文件，下载历史文件。
- 当前文件传输状态
附加说明：
a、上传下载CGI由governance提供。
b、将weevent-broker里的文件上传下载CGI挪到Governance，Broker服务以后和文件上传下载完全无关。
c、和区块链的交互依赖weevent-file.jar。
d、weevent-client.jar里文件上传和下载的逻辑会被weevent-file和Governance吸收。 weevent-client.jar以后和文件上传下载完全无关。

**Comment by anyspa** [comment]
PR #597
