### ISSUE TITLE
新增WeEvent Sample

### ISSUE THREAD

**Issue by caseone** [WeBankFinTech/WeEvent#643]
方便用户部署完成后即时体验WeEvent功能，同时也可作为开发demo便于用户快速上手开发业务
	命令行工具：创建topic、发布、订阅、查看容量等
	可视界面：用户可选，用户部署Governance即可（本版本无改动）
	github repo： https://github.com/WeBankFinTech/WeEvent-Sample

**Comment by anyspa** [comment]
https://github.com/WeBankFinTech/WeEvent-Sample
