### ISSUE TITLE
jms依赖库优化

### ISSUE THREAD

**Issue by caseone** [WeBankFinTech/WeEvent#645]
**Is your feature request related to a problem? Please describe.**
当前jms是依赖的jboss仓库（其他仓库没有jar包只有pom），gradle中把jboss仓库写在了阿里云仓库前面，这样的话所有依赖都从jboss下载；

**Describe the solution you'd like**
优化为只让jms依赖jboss库，其他的依赖阿里云仓库，提升下载依赖的速度

**Comment by yangaobiao** [comment]
complete

**Comment by yangaobiao** [comment]
complete

**Comment by yangaobiao** [comment]
complete

**Comment by yangaobiao** [comment]
complete
