### ISSUE TITLE
MQTT连接被动关闭的时候，没有取消这个连接上的订阅

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#77]
**Describe the bug**
MQTT的订阅是基于连接的。连接被动关闭的时候，服务端需要自动取消这个连接上的所有订阅。

**To Reproduce**
1. 建立MQTT连接，订阅主题
2. 客户端断开连接后，服务端Consumer还一直在事件通知onEvent

**Expected behavior**
MQTT连接被动关闭的时候，服务端需要自动取消这个连接上的所有订阅

**Comment by WeWebsterchen** [comment]
# was fix

**Comment by saintping** [comment]
已经合入PR#93
