### ISSUE TITLE
Governance的配置文件格式从.yml改成.properties

### ISSUE THREAD

**Issue by saintping** [WeBankFinTech/WeEvent#99]
**Is your feature request related to a problem? Please describe.**
Governance的进程配置文件是application.yml格式，一键脚本等自动化bash处理程序编辑不方便。

**Describe the solution you'd like**
和Broker进程一致。改为.properties格式。

**Comment by puremilkfan** [comment]
Is your feature request related to a problem? Please describe.
Governance的进程配置文件是application.yml格式，一键脚本等自动化bash处理程序编辑不方便。

Describe the solution you'd like
和Broker进程一致。改为.properties格式。
1.将yml文件改为properties文件，
2.调整文件格式
3.启动项目进行测试，确保项目正常运行
